# Generated by Django 5.0.6 on 2026-05-18 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.SmallIntegerField(choices=[(0, 'Полное забывание'), (1, 'Плохо'), (2, 'Неудовлетворительно'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Оценка качества ответа')),
                ('easiness_factor', models.FloatField(default=2.5, verbose_name='Коэффициент лёгкости (EF)')),
                ('interval_days', models.PositiveIntegerField(default=1, verbose_name='Интервал (дни)')),
                ('repetitions', models.PositiveIntegerField(default=0, verbose_name='Номер повторения')),
                ('next_review', models.DateField(verbose_name='Дата следующего повторения')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время повторения')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cards.card', verbose_name='Карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись повторения',
                'verbose_name_plural': 'Записи повторений',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['user', 'next_review'], name='reviews_rev_user_id_c5ecd6_idx'), models.Index(fields=['user', 'card', '-reviewed_at'], name='reviews_rev_user_id_6ccfb5_idx')],
            },
        ),
    ]
