# Generated by Django 5.0.6 on 2026-05-29 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1–5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='decks.deck', verbose_name='Колода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка колоды',
                'verbose_name_plural': 'Оценки колод',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('add', 'Добавить карточку'), ('edit', 'Изменить карточку'), ('delete', 'Удалить карточку')], max_length=10, verbose_name='Тип предложения')),
                ('front', models.TextField(blank=True, default='', verbose_name='Лицевая сторона')),
                ('back', models.TextField(blank=True, default='', verbose_name='Оборотная сторона')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий автора')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Автор предложения')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='cards.card', verbose_name='Карточка')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='decks.deck', verbose_name='Колода')),
            ],
            options={
                'verbose_name': 'Предложение улучшения',
                'verbose_name_plural': 'Предложения улучшений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='deckrating',
            constraint=models.UniqueConstraint(fields=('deck', 'user'), name='unique_deck_rating'),
        ),
    ]
